# Gradle
	org.gradle.jvmargs=-Xmx4G
	org.gradle.parallel=true
	org.gradle.caching=true

# Plugin Properties
	plugin_id=unplugged_afk
	plugin_name=UnpluggedAFK
	plugin_author=sakura-ryoko
	plugin_version=0.3.0
	maven_group=com.sakuraryoko
	archives_base_name=unplugged-afk

# Paper
	# https://fill.papermc.io/v3/projects/paper/versions
	minecraft_version=26.2
	# https://repo.papermc.io/repository/maven-public/io/papermc/paper/dev-bundle/
	paper_dev_bundle=26.2.build.112-stable
	# https://plugins.gradle.org/plugin/io.papermc.paperweight.userdev
	paperweight_version=2.0.0-beta.21
	# https://plugins.gradle.org/plugin/xyz.jpenilla.run-paper
	runpaper_version=3.0.2
	java_version=25
